return {
	"mrjones2014/smart-splits.nvim",
	lazy = false,
	config = function()
		require("smart-splits").setup({
			at_edge = "stop",
		})
	end,
	keys = {
		{
			"<C-h>",
			function()
				require("smart-splits").move_cursor_left()
			end,
		},
		{
			"<C-j>",
			function()
				require("smart-splits").move_cursor_down()
			end,
		},
		{
			"<C-k>",
			function()
				require("smart-splits").move_cursor_up()
			end,
		},
		{
			"<C-l>",
			function()
				require("smart-splits").move_cursor_right()
			end,
		},
		{
			"<C-Left>",
			function()
				require("smart-splits").resize_left()
			end,
		},
		{
			"<C-Down>",
			function()
				require("smart-splits").resize_down()
			end,
		},
		{
			"<C-Up>",
			function()
				require("smart-splits").resize_up()
			end,
		},
		{
			"<C-Right>",
			function()
				require("smart-splits").resize_right()
			end,
		},
	},
}
