shell zsh
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        family="JetBrainsMonoNL Nerd Font Mono" style=Regular
italic_font      family="JetBrainsMonoNL Nerd Font Mono" style=Regular
bold_italic_font auto
disable_ligatures always

hide_window_decorations yes
macos_show_window_title_in none
window_padding_width 5 2 0 2

background_opacity 0.8
background_blur 40
confirm_os_window_close 0
scrollback_lines 5000

resize_in_steps no
linux_display_server wayland
map ctrl+super+left no_op
map ctrl+super+right no_op
map ctrl+super+up no_op
map ctrl+super+down no_op

shell_integration enabled
shell tmux new-session -A -s 0default

# Added by Gogh
include colors.conf

include platform.conf
